### ISSUE TITLE
[master regression] Configuration offset "safe_parameters" does not exist. Known offsets: "executor"

### ISSUE THREAD

**Issue by tillkruss** [phpbench/phpbench#876] opened 2021-06-23 20:56 UTC
`dev-master` is broken for me, but 4ecdb15aa9e44fd091864ab2c048c408bc2f627c works.

Is this a configuration issue on my end?

```
\Relay\Benchmarks\MgetBench::benchMgetUsingPredis

    InvalidArgumentException Configuration offset "safe_parameters" does not exist. Known offsets: "executor"

    #0 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Executor/Benchmark/TemplateExecutor.php(117): PhpBench\Registry\Config->offsetGet('safe_parameters')
    #1 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Executor/Benchmark/TemplateExecutor.php(107): PhpBench\Executor\Benchmark\TemplateExecutor->resolveParameterSet(Object(PhpBench\Executor\ExecutionContext), Object(PhpBench\Registry\Config))
    #2 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Executor/Benchmark/TemplateExecutor.php(52): PhpBench\Executor\Benchmark\TemplateExecutor->createTokens(Object(PhpBench\Executor\ExecutionContext), Object(PhpBench\Registry\Config))
    #3 /Users/Till/Development/Repositories/relay/src/PhpBench/RedisExecutor.php(50): PhpBench\Executor\Benchmark\TemplateExecutor->execute(Object(PhpBench\Executor\ExecutionContext), Object(PhpBench\Registry\Config))
    #4 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Benchmark/Runner.php(366): Relay\PhpBench\RedisExecutor->execute(Object(PhpBench\Executor\ExecutionContext), Object(PhpBench\Registry\Config))
    #5 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Benchmark/Runner.php(308): PhpBench\Benchmark\Runner->runIteration(Object(Relay\PhpBench\RedisExecutor), Object(PhpBench\Registry\Config), Object(PhpBench\Model\Iteration), Object(PhpBench\Benchmark\Metadata\SubjectMetadata))
    #6 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Benchmark/Runner.php(279): PhpBench\Benchmark\Runner->runVariant(Object(Relay\PhpBench\RedisExecutor), Object(PhpBench\Registry\Config), Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Benchmark\Metadata\SubjectMetadata), Object(PhpBench\Model\Variant))
    #7 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Benchmark/Runner.php(197): PhpBench\Benchmark\Runner->runSubject(Object(Relay\PhpBench\RedisExecutor), Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Model\Subject), Object(PhpBench\Benchmark\Metadata\SubjectMetadata))
    #8 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Benchmark/Runner.php(123): PhpBench\Benchmark\Runner->runBenchmark(Object(PhpBench\Benchmark\RunnerConfig), Object(PhpBench\Model\Benchmark), Object(PhpBench\Benchmark\Metadata\BenchmarkMetadata))
    #9 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Console/Command/Handler/RunnerHandler.php(141): PhpBench\Benchmark\Runner->run(Object(Generator), Object(PhpBench\Benchmark\RunnerConfig))
    #10 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/Console/Command/RunCommand.php(134): PhpBench\Console\Command\Handler\RunnerHandler->runFromInput(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(PhpBench\Benchmark\RunnerConfig))
    #11 /Users/Till/Development/Repositories/relay/vendor/symfony/console/Command/Command.php(299): PhpBench\Console\Command\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
    #12 /Users/Till/Development/Repositories/relay/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
    #13 /Users/Till/Development/Repositories/relay/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(PhpBench\Console\Command\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
    #14 /Users/Till/Development/Repositories/relay/vendor/symfony/console/Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
    #15 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/lib/PhpBench.php(51): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput))
    #16 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/bin/phpbench.php(25): PhpBench\PhpBench::run()
    #17 /Users/Till/Development/Repositories/relay/vendor/phpbench/phpbench/bin/phpbench(4): require('/Users/Till/Dev...')
    #18 {main}
```

**Comment by dantleech** [comment] 2021-06-25 14:37
This is because you are not calling `parent::configure()` in your `RedisExecutor` I think

**Comment by dantleech** [comment] 2021-06-26 16:42
"regression" fixed in https://github.com/phpbench/phpbench/commit/1ee8a10d2e3210307ab5fc962ec5d3e7297651c8 assuming it was because you overrode the `configure` method and forgot to call `parent::`?

**Closed by dantleech** 2021-06-26 16:42 UTC
Labels: bug
