### ISSUE TITLE
InvalidArgumentException: Result of class "PhpBench\Model\Result\TimeResult" has already been set.

### ISSUE THREAD

**Issue by WouterJ** [phpbench/phpbench#423] opened 2016-06-26 10:32 UTC
`array-count.php`
```php
<?php

class ArrayCountBench
{
    private $zero = [];
    private $full = [1, 2, 3, 4];

    /**
     * @Revs(1000)
     * @Iterations(5)
     */
    public function benchCount()
    {
        0 === count($this->zero);
        0 === count($this->full);
    }

    /**
     * @Revs(1000)
     * @Iterations(5)
     */
    public function benchFalsey()
    {
        !$this->zero;
        !$this->full;
    }
}
```

Terminal:
```
C:\web>phpbench run array-count.php --retry-threshold=5 --report=aggregate
PhpBench 0.12-dev (93e3e87). Running benchmarks.

\ArrayCountBench

    benchCount                    R2 I1 P0

  [InvalidArgumentException]
  Result of class "PhpBench\Model\Result\TimeResult" has already been set.


run [--filter FILTER] [--group GROUP] [--parameters PARAMETERS] [--revs REVS] [-l|--progress PROGRESS] [-b|--bootstrap B
OOTSTRAP] [--executor EXECUTOR] [--stop-on-error] [--php-binary PHP-BINARY] [--php-config PHP-CONFIG] [--php-wrapper PHP
-WRAPPER] [--report REPORT] [-o|--output OUTPUT] [--time-unit TIME-UNIT] [--precision PRECISION] [--mode MODE] [-d|--dum
p-file [DUMP-FILE]] [--dump] [--iterations ITERATIONS] [--warmup WARMUP] [-r|--retry-threshold RETRY-THRESHOLD] [--sleep
 SLEEP] [--context CONTEXT] [--store] [--] [<path>]
```
```
C:\web>phpbench run array-count.php --retry-threshold=5 --report=aggregate -vvv
PhpBench 0.12-dev (93e3e87). Running benchmarks.

\ArrayCountBench

    benchCount                    I4 P0         [╬╝ Mo]/r: 0.251 0.248 (╬╝s)    [╬╝SD ╬╝RSD]/r: 0.006╬╝s 2.57%
    benchFalsey                   R1 I0 P0

  [InvalidArgumentException]
  Result of class "PhpBench\Model\Result\TimeResult" has already been set.


Exception trace:
 () at phar://C:/web/bin/phpbench.phar/lib/Model/ResultCollection.php:43
 PhpBench\Model\ResultCollection->addResult() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Executor/MicrotimeExecuto
r.php:46
 PhpBench\Benchmark\Executor\MicrotimeExecutor->launch() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Executor/BaseE
xecutor.php:68
 PhpBench\Benchmark\Executor\BaseExecutor->execute() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Runner.php:229
 PhpBench\Benchmark\Runner->runIteration() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Runner.php:218
 PhpBench\Benchmark\Runner->runVariant() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Runner.php:178
 PhpBench\Benchmark\Runner->runSubject() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Runner.php:149
 PhpBench\Benchmark\Runner->runBenchmark() at phar://C:/web/bin/phpbench.phar/lib/Benchmark/Runner.php:101
 PhpBench\Benchmark\Runner->run() at phar://C:/web/bin/phpbench.phar/lib/Console/Command/Handler/RunnerHandler.php:86
 PhpBench\Console\Command\Handler\RunnerHandler->runFromInput() at phar://C:/web/bin/phpbench.phar/lib/Console/Command/R
unCommand.php:82
 PhpBench\Console\Command\RunCommand->execute() at phar://C:/web/bin/phpbench.phar/vendor/symfony/symfony/src/Symfony/Co
mponent/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar://C:/web/bin/phpbench.phar/vendor/symfony/symfony/src/Symfony/
Component/Console/Application.php:815
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/web/bin/phpbench.phar/vendor/symfony/symfony/src/Sym
fony/Component/Console/Application.php:186
 Symfony\Component\Console\Application->doRun() at phar://C:/web/bin/phpbench.phar/vendor/symfony/symfony/src/Symfony/Co
mponent/Console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/web/bin/phpbench.phar/lib/PhpBench.php:57
 PhpBench\PhpBench::run() at phar://C:/web/bin/phpbench.phar/bin/phpbench.php:22
 require() at C:\web\bin\phpbench.phar:11

run [--filter FILTER] [--group GROUP] [--parameters PARAMETERS] [--revs REVS] [-l|--progress PROGRESS] [-b|--bootstrap B
OOTSTRAP] [--executor EXECUTOR] [--stop-on-error] [--php-binary PHP-BINARY] [--php-config PHP-CONFIG] [--php-wrapper PHP
-WRAPPER] [--report REPORT] [-o|--output OUTPUT] [--time-unit TIME-UNIT] [--precision PRECISION] [--mode MODE] [-d|--dum
p-file [DUMP-FILE]] [--dump] [--iterations ITERATIONS] [--warmup WARMUP] [-r|--retry-threshold RETRY-THRESHOLD] [--sleep
 SLEEP] [--context CONTEXT] [--store] [--] [<path>]
```

**Comment by dantleech** [comment] 2016-06-26 11:48
This is caused by the retry-threshold. I recently did a major refactoring of the result collection, and seems `retry-threshold` is not adequately tested here.

**Comment by dantleech** [comment] 2016-06-26 12:27
Will be fixed by https://github.com/phpbench/phpbench/pull/424

**Closed** 2016-06-26 12:50 UTC

**Comment by dantleech** [comment] 2016-06-26 12:52
Fixed - btw can you 

- confirm that the (runner) performance is terrible on Windows? It currently uses more process creation than neeed and I am consdering reducing 2-3 times if it makes a big difference on Windows.
- let me know your experience with the progress logger formatting?
