### ISSUE TITLE
General discussion for usability

### ISSUE THREAD

**Issue by redaxmedia** [phpbench/phpbench#183] opened 2015-11-01 11:42 UTC
I'd like to suggest a couple of usability issues that came up using PHPBench for the first time:

1. There should be a setUp() and tearDown() etc. by default - I don't like to add
<code>@BeforeMethods({"setUp"})</code> to every docblock

2. The syntax of the data-provider was confusing to me - you should stick to PHPUnit and provide <code>$param1, $param2 and $param3</code> instead of the single <code>$params</code> array

3. Is there a way to use PHPBench with a continuous integration service like Travis CI? If not, I suggest you add something like a threshold that returns an error code if the benchmarks failed

4. Tabular is great but you should truncate values that are longer than 20 characters:
http://i.snag.gy/UNsRd.jpg

5. Please use semantic versioning... 0.6.0 instead of 0.6

Keep in mind, this is just a discussion - please create new issues for each one of the issues

Thank you

**Comment by dantleech** [comment] 2015-11-01 20:26
> There should be a setUp() and tearDown() etc. by default - I don't like to add
@BeforeMethods({"setUp"}) to every docblock

You can add this annotation to the class docblock, if you want all of your classes to have a `setUp` and `tearDown` you can define a single base class which your benchmarks extend, and annotate that.

````php
/**
 * My base benchmark
 * @BeforeMethods({"setUp"})
 */
````

Basically I wanted to avoid magic (checking if a method exists and then executing it if it does).

> The syntax of the data-provider was confusing to me - you should stick to PHPUnit and provide $param1, $param2 and $param3 instead of the single $params array

Will have to think about that. PHPBench is different from PHPUnit in that it provides always an associative array for data - and allows you to specify multiple parameter providers and provide data sets using all possible combinations. For this associative arrays are better I think. But lets discuss.

> Is there a way to use PHPBench with a continuous integration service like Travis CI? If not, I suggest you add something like a threshold that returns an error code if the benchmarks failed

The problem with Travis CI is that it is not designed to run at a consistent speed. You may get different times for each build using the same code. It would be nice to create a system using VMs which gurantee resources and so provide a stable platform, but I havn't looked into this much yet.

> Tabular is great but you should truncate values that are longer than 20 characters

The problem is that we don't know which part of that string is relevant. Could you create an issue for this?

> Semantic versioning.

I am currently just increasing by 0.1 each time until the 1.0 release, where I semver will be started properly - basically BC can be broken at any point before 1.0, so not sure that managing patch versions is relevant (?)

**Comment by redaxmedia** [comment] 2015-11-02 08:16
Thank you for the extensive response.

1. Your solution for the setUp and tearDown is okay for me, because I extend each benchFoobar from a BenchCase class. Most people will not have such a thing and feel uncomfortable, you call it magic but this is more like a de facto standard in all testing frameworks.

2. All right!

3. I can understand this, maby you write a internal test just for a "CI mode" that is calculating the speed of the current system - this are the 100% of speed and following tests are related to it?

4. I can create an issue on Tabular.

5. I think it always makes sence to use it, even in the beta phase. It was not clear to me (and maby most other people) that BC can be broken at any point.

**Comment by dantleech** [comment] 2015-11-04 13:46
> 1

PHPBench can have multiple "before" methods, so you could declare {"foobar"} and not declare "setUp" and it would run both "foobar" and "setUp". i.e. it provides two ways of doing things. I would prefer to only support explict. Perhaps there should be an FAQ explaining how to simply emulate this behavior using an abstract class?

> 2

Could you create an issue to discuss further?

> 3. I can understand this, maby you write a internal test just for a "CI mode" that is calculating the speed of the current system 

I thought about doing this in #81 , but it is not so simple, as it is not just processing speed, but also hard drive speed etc. So creating some sort of calibration metric would be difficult imo. Maybe something that can be looked at later, but I would guess it would be inherently unstable.

Adding some sort of "fail" threshold could be done, but without a stable platform it would be useless.

> 4.

I created #184 in phpbench

**Comment by redaxmedia** [comment] 2015-11-04 17:07
1. It is great to have a feature like that but still I would stick to the way most testing frameworks are made, if you don't believe me so believe athletic: https://github.com/polyfractal/athletic#setups-and-teardowns :-)

2. I just created #188

3. You can drop the idea, but still it would be great to have a useful way to put PHPBench into the CI process.

**Comment by dantleech** [comment] 2015-11-04 21:35
For 3 -- One approach to this would be to have the ability to compare results and fail based on a comparison. 

For example, in your CI process, checkout branch `master`, run the benchmarking suite, then checkout git branch my_feature, and run the benchmarking suite (dumping the results of both suites to XML files). You could then run `phpbench compare resultset1.xml resultset2.xml` and it would dump a report showing the differences, and exit with an error code if a certain threshold is exceeded. This approach would be fairly stable on travis, especially with the introduction of #186

**Comment by redaxmedia** [comment] 2015-11-05 09:31
Usually only a single branch will be cloned in a CI process, a setup like that is possible but sounds quite complicated unless you have a service where you can put your results to.

**Comment by dantleech** [comment] 2015-11-05 20:11
Yes, using Travis CI it would potenentially double the build time
(having to composer install two branches). The best thing would be to
use a separate CI service for benchmarks (i.e. custom server with
Jenkins). But I think the feature for comparing two separate results
would be a solution for performance regression testing. Ultimately it
would be good to have a BenchCI service :)

**Comment by dantleech** [comment] 2015-11-06 10:24
Regarding 1: I have added an [FAQ](https://github.com/phpbench/phpbench/pull/189/files#diff-c6f0a0722c6a2f86277535d7bcec7f8cR4). Basically:

- There is a parity mismatch between multiple before methods indicated by annotations and a single "magic" method which requires no annotation
- Multiple before/after methods are required to have different before and after methods on different subject methods.
- `setUp` and `tearDown` could conflict with a PHPUnit test case if you were crazy enough for them to share the same class (which you can do).

For 2: I created https://github.com/phpbench/phpbench/issues/190

Closing this now, feel free to reopen if required or create a new issue.

**Closed by dantleech** 2015-11-06 10:24 UTC

**Comment by redaxmedia** [comment] 2015-11-06 16:42
Sorry but the <code>setUp</code> and <code>tearDown</code> workarround using a base bench class does not work for me.

1. Current setup:
 - <code>BenchCase</code> class: http://pastebin.com/rc7njZU1
 - <code>HashBench</code> class: http://pastebin.com/aGBtBRyn

2. Suggested setup:
 - <code>BenchCase</code> class: http://pastebin.com/PL1YCUN9
 - <code>HashBench</code> class: http://pastebin.com/FDJwd4Zx

PHPBench returns a RuntimeException: could not launch script: http://i.snag.gy/qh9u2.jpg

**Comment by dantleech** [comment] 2015-11-06 16:51
It should work. Is the base class included/required/autoloaded? In
anycase there would seem to be a bug with showing the actual error
message - could you trace it? (I get error messages here if the class is
not found).

**Comment by redaxmedia** [comment] 2015-11-07 09:38
The base class is included, how can I log the whole debug information for a bug report?
Should I open a new issue?

**Comment by dantleech** [comment] 2015-11-07 09:56
If you could create a failing test, or point me to some code I could checkout that would be great. 

Otherwise you can use the `--verbose` flag to get a stack trace, from which you will be able to see the class and line that the sub-process is executed, and debug from there. After we have estabilished the cause we should create the issue.

**Comment by dantleech** [comment] 2015-11-07 15:37
I encountered a similar issue and fixed it with https://github.com/phpbench/phpbench/pull/193 - but still not sure why you didn't receive an error message.
