### ISSUE TITLE
--revs=1 --iterations==1 may lead to 'Division by zero'

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#506] opened 2018-01-03 00:46 UTC
I wanted to get a quick overview about a benchmark set from third party. So I started the benchmarks with revolutions and iterations both set to 1. This leads to 'TableGenerator, line 153: Division by zero'. 
--report=aggregate and --progress=blinken btw.

Not a meaningful setting if it is about benchmarking. But I just wanted to get a picture of the structure without the need to inspect the code.

I'd propose, that TableGenerator should set a discrete value (meaning 'not computable' or 'not available' or 'infinite' or such) instead of exiting with error.

**Comment by dantleech** [comment] 2018-01-03 08:53
Hey, I tried to reproduce using the following (which will produce a result set where every time is zero):

```
$ ./bin/phpbench run --iterations=1 --revs=1 --executor='{"extends":"debug", "times": [ 0 ], "spread": [0]}' --report=aggregate --report=default
```

But I cannot. I seem to remember having this issue on Windows before however, can you provide a stack trace?

**Comment by fhein** [comment] 2018-01-05 00:30
Interestingly, this error does not occur with -vvv set, so I can not effortlessly produce that trace.
Maybe, this vanishing error is just hint enough. 

To reproduce, get [zend-servicemanager](https://github.com/zendframework/zend-servicemanager).
I ran it's benchmarks.

Here's a transcript of what I did ( I added blinken for your convenience):

	$ vendor\bin\phpbench run --report=aggregate --iterations=1 --revs=1 --progress=blinken
	PhpBench 0.13.0. Running benchmarks.
	Using configuration file: C:\project/phpbench.json

	\ZendBench\ServiceManager\FetchCachedServicesBench (#0 benchFetchFactory1, #1 benchFetchInvokable1, #2 benchFetchService1, #3 benchFetchAlias1, #4 benchFetchRecursiveAlias1, #5 benchFetchRecursiveAlias2, #6 benchFetchAbstractFactoryService)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServicesBench (#0 benchFetchFactory1, #1 benchBuildFactory1, #2 benchFetchInvokable1, #3 benchBuildInvokable1, #4 benchFetchService1, #5 benchFetchFactoryAlias1, #6 benchBuildFactoryAlias1, #7 benchFetchRecursiveFactoryAlias1, #8 benchBuildRecursiveFactoryAlias1, #9 benchFetchRecursiveFactoryAlias2, #10 benchBuildRecursiveFactoryAlias2, #11 benchFetchAbstractFactoryFoo, #12 benchBuildAbstractFactoryFoo)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#7  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#8  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#9  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#10 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#11 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#12 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceViaConfigAbstractFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  1,000 (µs) [µ Mo]/r: 1,000.000 1,000.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceViaReflectionAbstractFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\HasBench (#0 benchHasFactory1, #1 benchHasInvokable1, #2 benchHasService1, #3 benchHasAlias1, #4 benchHasRecursiveAlias1, #5 benchHasRecursiveAlias2, #6 benchHasAbstractFactory, #7 benchHasNot)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#7  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\SetNewServicesBench (#0 benchSetFactory, #1 benchSetAlias, #2 benchSetAliasOverrided)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	55 subjects, 55 iterations, 55 revs, 0 rejects
	(best [mean mode] worst) = 0.000 [18.182 18.182] 0.000 (µs)
	?T: 1,000.000µs µSD/r 0.000µs µRSD/r: 0.000%

	In TableGenerator.php line 153:

	  Warning: Division by zero


	run [--filter FILTER] [--group GROUP] [--parameters PARAMETERS] [--revs REVS] [-l|--progress PROGRESS] [-b|--bootstrap BOOTSTRAP] [--executor EXECUTOR] [--stop-on-error] [--php-binary PHP-BINARY] [--php-config PHP-CONFIG] [--php-wrapper PHP-WRAPPER] [--report REPORT] [-o|--output OUTPUT] [--time-unit TIME-UNIT] [--precision PRECISION] [--mode MODE] [-d|--dump-file [DUMP-FILE]] [--dump] [--iterations ITERATIONS] [--warmup WARMUP] [-r|--retry-threshold RETRY-THRESHOLD] [--sleep SLEEP] [--context CONTEXT] [--store] [--] [<path>]

**Comment by fhein** [comment] 2018-01-05 00:34
And heres the transcript with -vvv set. No error.

	$ vendor\bin\phpbench run --report=aggregate --iterations=1 --revs=1 --progress=blinken -vvv
	PhpBench 0.13.0. Running benchmarks.
	Using configuration file: C:\project/phpbench.json

	\ZendBench\ServiceManager\FetchCachedServicesBench (#0 benchFetchFactory1, #1 benchFetchInvokable1, #2 benchFetchService1, #3 benchFetchAlias1, #4 benchFetchRecursiveAlias1, #5 benchFetchRecursiveAlias2, #6 benchFetchAbstractFactoryService)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServicesBench (#0 benchFetchFactory1, #1 benchBuildFactory1, #2 benchFetchInvokable1, #3 benchBuildInvokable1, #4 benchFetchService1, #5 benchFetchFactoryAlias1, #6 benchBuildFactoryAlias1, #7 benchFetchRecursiveFactoryAlias1, #8 benchBuildRecursiveFactoryAlias1, #9 benchFetchRecursiveFactoryAlias2, #10 benchBuildRecursiveFactoryAlias2, #11 benchFetchAbstractFactoryFoo, #12 benchBuildAbstractFactoryFoo)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#7  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#8  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#9  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#10 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#11 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#12 0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceViaConfigAbstractFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\FetchNewServiceViaReflectionAbstractFactoryBench (#0 benchFetchServiceWithNoDependencies, #1 benchBuildServiceWithNoDependencies, #2 benchFetchServiceDependingOnConfig, #3 benchBuildServiceDependingOnConfig, #4 benchFetchServiceWithDependency, #5 benchBuildServiceWithDependency)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\HasBench (#0 benchHasFactory1, #1 benchHasInvokable1, #2 benchHasService1, #3 benchHasAlias1, #4 benchHasRecursiveAlias1, #5 benchHasRecursiveAlias2, #6 benchHasAbstractFactory, #7 benchHasNot)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#3  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#4  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#5  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#6  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#7  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	\ZendBench\ServiceManager\SetNewServicesBench (#0 benchSetFactory, #1 benchSetAlias, #2 benchSetAliasOverrided)

	#0  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#1  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%
	#2  0 (µs) [µ Mo]/r: 0.000 0.000 µRSD/r: 0.00%

	55 subjects, 55 iterations, 55 revs, 0 rejects
	(best [mean mode] worst) = 0.000 [0.000 0.000] 0.000 (µs)
	?T: 0.000µs µSD/r 0.000µs µRSD/r: 0.000%
	suite: 133ec89d0025bee325c25972efbe7b3fb757a341, date: 2018-01-05, stime: 00:31:40
	+-------------------------------------------------------------+-------------------------------------+--------+--------+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
	| benchmark                                                   | subject                             | groups | params | revs | its | mem_peak   | best    | mean    | mode    | worst   | stdev   | rstdev | diff  |
	+-------------------------------------------------------------+-------------------------------------+--------+--------+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+
	| FetchCachedServicesBench                                    | benchFetchFactory1                  |        | []     | 1    | 1   | 1,311,792b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchInvokable1                |        | []     | 1    | 1   | 1,311,792b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchService1                  |        | []     | 1    | 1   | 1,311,792b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchAlias1                    |        | []     | 1    | 1   | 1,311,792b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchRecursiveAlias1           |        | []     | 1    | 1   | 1,311,800b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchRecursiveAlias2           |        | []     | 1    | 1   | 1,311,800b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchCachedServicesBench                                    | benchFetchAbstractFactoryService    |        | []     | 1    | 1   | 1,311,808b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchFactory1                  |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildFactory1                  |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchInvokable1                |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildInvokable1                |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchService1                  |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchFactoryAlias1             |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildFactoryAlias1             |        | []     | 1    | 1   | 1,313,592b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchRecursiveFactoryAlias1    |        | []     | 1    | 1   | 1,313,608b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildRecursiveFactoryAlias1    |        | []     | 1    | 1   | 1,313,608b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchRecursiveFactoryAlias2    |        | []     | 1    | 1   | 1,313,608b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildRecursiveFactoryAlias2    |        | []     | 1    | 1   | 1,313,608b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchFetchAbstractFactoryFoo        |        | []     | 1    | 1   | 1,313,600b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServicesBench                                       | benchBuildAbstractFactoryFoo        |        | []     | 1    | 1   | 1,313,600b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchFetchServiceWithNoDependencies |        | []     | 1    | 1   | 1,316,672b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchBuildServiceWithNoDependencies |        | []     | 1    | 1   | 1,316,672b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchFetchServiceDependingOnConfig  |        | []     | 1    | 1   | 1,316,672b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchBuildServiceDependingOnConfig  |        | []     | 1    | 1   | 1,316,672b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchFetchServiceWithDependency     |        | []     | 1    | 1   | 1,316,664b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingConfigAbstractFactoryAsFactoryBench     | benchBuildServiceWithDependency     |        | []     | 1    | 1   | 1,316,664b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchFetchServiceWithNoDependencies |        | []     | 1    | 1   | 1,314,136b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchBuildServiceWithNoDependencies |        | []     | 1    | 1   | 1,314,136b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchFetchServiceDependingOnConfig  |        | []     | 1    | 1   | 1,314,136b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchBuildServiceDependingOnConfig  |        | []     | 1    | 1   | 1,314,136b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchFetchServiceWithDependency     |        | []     | 1    | 1   | 1,314,128b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceUsingReflectionAbstractFactoryAsFactoryBench | benchBuildServiceWithDependency     |        | []     | 1    | 1   | 1,314,128b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchFetchServiceWithNoDependencies |        | []     | 1    | 1   | 1,315,632b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchBuildServiceWithNoDependencies |        | []     | 1    | 1   | 1,315,632b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchFetchServiceDependingOnConfig  |        | []     | 1    | 1   | 1,315,632b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchBuildServiceDependingOnConfig  |        | []     | 1    | 1   | 1,315,632b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchFetchServiceWithDependency     |        | []     | 1    | 1   | 1,315,624b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaConfigAbstractFactoryBench                | benchBuildServiceWithDependency     |        | []     | 1    | 1   | 1,315,624b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchFetchServiceWithNoDependencies |        | []     | 1    | 1   | 1,313,160b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchBuildServiceWithNoDependencies |        | []     | 1    | 1   | 1,313,160b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchFetchServiceDependingOnConfig  |        | []     | 1    | 1   | 1,313,160b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchBuildServiceDependingOnConfig  |        | []     | 1    | 1   | 1,313,160b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchFetchServiceWithDependency     |        | []     | 1    | 1   | 1,313,152b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| FetchNewServiceViaReflectionAbstractFactoryBench            | benchBuildServiceWithDependency     |        | []     | 1    | 1   | 1,313,152b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasFactory1                    |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasInvokable1                  |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasService1                    |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasAlias1                      |        | []     | 1    | 1   | 1,312,344b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasRecursiveAlias1             |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasRecursiveAlias2             |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasAbstractFactory             |        | []     | 1    | 1   | 1,312,352b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| HasBench                                                    | benchHasNot                         |        | []     | 1    | 1   | 1,312,344b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| SetNewServicesBench                                         | benchSetFactory                     |        | []     | 1    | 1   | 1,374,864b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| SetNewServicesBench                                         | benchSetAlias                       |        | []     | 1    | 1   | 1,374,864b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	| SetNewServicesBench                                         | benchSetAliasOverrided              |        | []     | 1    | 1   | 1,374,872b | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.000µs | 0.00%  | 0.00% |
	+-------------------------------------------------------------+-------------------------------------+--------+--------+------+-----+------------+---------+---------+---------+---------+---------+--------+-------+

**Comment by dantleech** [comment] 2018-01-05 08:44
Hmm, cannot reproduce with Zend even if I hard-code the times to `0` (as above with the debug executor). Will install Windows and try it there...

**Comment by dantleech** [comment] 2021-05-01 18:01
The report that causes this error has been completely replaced, so closing now.

**Closed by dantleech** 2021-05-01 18:01 UTC
Labels: cannot reproduce
